CREATE TABLE DIRECTOR (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(25),
  LASTNAME VARCHAR(25),
  PRIMARY KEY (ID)
);

CREATE TABLE MOVIE (
  MOVIE_ID BIGINT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100),
  RELEASE_DATE DATE,
  RATING INTEGER,
  DIRECTOR_ID BIGINT,
  foreign key (DIRECTOR_ID) references director(ID)
);